version: "3.8" # 或者使用你需要的版本

services:
  aipan-netdisk-search:
    image: unilei/aipan-netdisk-search:latest # 如果你想从 Docker Hub 获取镜像，可以使用这一行
    container_name: aipan-netdisk-search-app
    restart: always # 确保容器在停止后自动重启
    build:
      context: . # 构建上下文，通常是 Dockerfile 所在的目录
      dockerfile: Dockerfile # Dockerfile 的名称
      args:
        ADMIN_USER: ${ADMIN_USER}
        ADMIN_PASSWORD: ${ADMIN_PASSWORD}
        ADMIN_EMAIL: ${ADMIN_EMAIL}
        JWT_SECRET: ${JWT_SECRET}
        DATABASE_URL: ${DATABASE_URL}
        DATABASE_SCHEMA: ${DATABASE_SCHEMA}
        SHADOW_DATABASE_URL: ${SHADOW_DATABASE_URL}
    ports:
      - "3000:3000" # 映射容器的 3000 端口到宿主机的 3000 端口
    env_file:
      - .env
    depends_on:
      - db
      - prisma-migrate

  db:
    image: postgres:15-alpine
    container_name: aipan-netdisk-search-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-netdisk}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  prisma-migrate:
    image: node:20.18.0-alpine
    container_name: aipan-netdisk-search-migrate
    command: >
      sh -c '
      npm install prisma --no-save &&
      if ! npx prisma migrate status | grep -q "Database schema is up to date"; then
        echo "Running database migrations..." &&
        npx prisma migrate deploy
      else
        echo "Database schema is already up to date, skipping migrations."
      fi
      '
    working_dir: /app
    volumes:
      - ./prisma:/app/prisma
      - ./.env:/app/.env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db

volumes:
  postgres_data:
